### ISSUE TITLE
ArrayIndexOutOfBoundException

### ISSUE THREAD

**Issue by triandamai** [Creative-Motion-Apps/Kotlin-Ecg-Detectors#1]
Hi
I am trying to use this library for my project then I got an error :

```java
java.lang.ArrayIndexOutOfBoundsException: length=58; index=58
        at com.motionapps.kotlin_ecg_detectors.Utils.addingZeros(Utils.kt:65)
        at com.motionapps.kotlin_ecg_detectors.Detectors.engzeeDetector(Detectors.kt:271)
        at com.motionapps.kotlin_ecg_detectors.Detectors.engzeeDetector$default(Detectors.kt:25
```
please tell me what suppose I do :sad:

**Comment by Foxpace** [comment]
I updated dependencies and did some minor changes for some methods to check array bounds. The dependency to this code also changed -> refer to the [README.md](https://github.com/Foxpace/Kotlin-Ecg-Detectors#gradle-version). 

If the error occures after the update, please post here how to replicate your error + data/signal. Thanks.

**Comment by triandamai** [comment]
@Foxpace  Okay, I'll try

**Comment by triandamai** [comment]
I though you can add some unit test there before release new update 😂

**Comment by Foxpace** [comment]
> I though you can add some unit test there before release new update 😂

The tests are in place, but the data source used by them is private, so they cannot be public. I will release them in near future, if I use other public database, so there is no confusion.

**Comment by triandamai** [comment]
> > I though you can add some unit test there before release new update 😂
> 
> The tests are in place, but the data source used by them is private, so they cannot be public. I will release them in near future, if I use other public database, so there is no confusion.

I seee ...

**Comment by triandamai** [comment]
Ah btw, your update just saved my life 😄 
Thank's
